version: "3.8"
services:
  gymbro-login:
    build: .
    ports:
      - "${PORT}:3030"
    environment:
      - LOCAL=${LOCAL}
      - PEPPER=${PEPPER}
      - ENV=${ENV}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
